### PR TITLE
Fix docker image build

### LINKED ISSUE #107: Unable to build the docker image
## Logs

```
Staging lndmanage source code...
Building lndmanage docker container...
Sending build context to Docker daemon  1.554MB
Step 1/20 : FROM python:3 as builder
 ---> e2e732b7951f
Step 2/20 : RUN python -m venv /root/.venv
 ---> Using cache
 ---> 47777819d9d0
Step 3/20 : ENV PATH="/root/.venv/bin:$PATH"
 ---> Using cache
 ---> 3afe8642195e
Step 4/20 : ARG LNDMANAGE_HOST_SRC_PATH
 ---> Using cache
 ---> a65ed58bb47e
Step 5/20 : COPY "$LNDMANAGE_HOST_SRC_PATH/requirements.txt" .
 ---> Using cache
 ---> accbd970675a
Step 6/20 : RUN pip install wheel && pip install -r requirements.txt
 ---> Running in 8acf63bff7a4
Collecting wheel
  Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel
Successfully installed wheel-0.37.1
WARNING: You are using pip version 21.2.4; however, version 22.0.2 is available.
You should consider upgrading via the '/root/.venv/bin/python -m pip install --upgrade pip' command.
ERROR: Directory '.' is not installable. Neither 'setup.py' nor 'pyproject.toml' found.
WARNING: You are using pip version 21.2.4; however, version 22.0.2 is available.
You should consider upgrading via the '/root/.venv/bin/python -m pip install --upgrade pip' command.
The command '/bin/sh -c pip install wheel && pip install -r requirements.txt' returned a non-zero code: 1
```

## Steps to reproduce

- `cd docker`
- `bash build.sh`

## Environment

- lndmanage version: v0.14.0
- OS: Ubuntu 20.04.3 LTS
- Docker version: 20.10.7

### PR DESCRIPTION
**Pull request by 3nprob**
Fix #107

### CODE REVIEW

File: docker/build.sh [hunk 1]
```diff
@@ -24,7 +23,7 @@ echo "Building lndmanage docker container..."
 if [[ -n "$LNDMANAGE_VERBOSE" ]]; then
   set -x
 fi
-exec docker build \
+exec sudo docker build \
```
Comment (bitromortac) [inline docker/build.sh]: I think running this as root should not be necessary, it's just a group permission issue that the user should belong to the docker group, right?

File: docker/lndmanage/Dockerfile [hunk 2]
```diff
@@ -3,15 +3,19 @@
 
 FROM python:3 as builder
 
-RUN python -m venv /root/.venv
+RUN python -m venv /root/.venv && mkdir lndmanage
```
Comment (bitromortac) [inline docker/lndmanage/Dockerfile]: seems like that change is not neccessary, although it is explicit

File: docker/lndmanage/Dockerfile [hunk 3]
```diff
@@ -3,15 +3,19 @@
...
 ARG LNDMANAGE_HOST_SRC_PATH
 
 COPY "$LNDMANAGE_HOST_SRC_PATH/requirements.txt" .
+COPY "$LNDMANAGE_HOST_SRC_PATH/pyproject.toml" .
+COPY "$LNDMANAGE_HOST_SRC_PATH/setup.py" .
+COPY "$LNDMANAGE_HOST_SRC_PATH/README.md" .
+COPY "$LNDMANAGE_HOST_SRC_PATH/lndmanage/__init__.py" ./lndmanage/
 
-RUN pip install wheel && pip install -r requirements.txt
+RUN pip install --upgrade pip setuptools wheel && pip install .
```
Comment (bitromortac) [inline docker/lndmanage/Dockerfile]: you can remove `setuptools` and `wheel`, that is taken care about by `pyproject.toml`, I should probably remove it from the main readme as well

File: docker/lndmanage/Dockerfile [hunk 4]
```diff
@@ -39,7 +43,7 @@ ARG LNDMANAGE_HOST_SRC_PATH
 COPY "$LNDMANAGE_HOST_SRC_PATH" .
 
 # this should be fast because it is cached from builder image
-RUN pip install -r requirements.txt
```
Comment (bitromortac) [inline docker/lndmanage/Dockerfile:44]: I think we should be able to remove that whole install instruction, since we run `./lndmanage.py` directly, without installing into the virtual environment and therefore we don't create an alias `lndmanage`, see `run-lndmanage`.

**Review by bitromortac — COMMENTED** [review]
Thank you for the PR, that helps a lot!

**Comment by bitromortac** [comment]
Hey @3nprob, will you get around making the changes? I could take over if you don't have the time to.

**Comment by 3nprob** [comment]
Hi @bitromortac , apologies for the holdup, on it

File: docker/build.sh (hunk 1 above)
Comment (3nprob) [reply docker/build.sh]: One could argue both ways - I'm of the opinion that:
* docker group permissions almost always imply root-level access any way, so not much if any security is gained that way in practice 
* using sudo here instead means that the permission is scoped to this line and the rest of `build.sh` can run with reduced privileges, thereby minimizing exposed surface

But at the end of the day both approaches are valid and matter of opinion, so I'll leave the final call to you as the maintainer

File: docker/build.sh [hunk 5]
```diff
@@ -14,7 +14,6 @@ rsync -a \
   --exclude='.idea/' \
   --exclude='docker/' \
   --exclude='cache/' \
-  --exclude='README.md' \
```
Comment (3nprob) [inline docker/build.sh:17]: @bitromortac How do you feel about just excluding README.md from the docker build alltogether? That is, the package generated in the image would have `long_description` fall back to be equal to `description`, as opposed to containing the whole readme. Would reduce image size and make the build a bit cleaner, but if you feel strongly about keeping the build result identical, I'll keep it

File: docker/build.sh (hunk 1 above)
Comment (3nprob) [reply docker/build.sh]: You know what nvm, shouldn't assume sudo package is installed just for this

**Comment by 3nprob** [comment]
@bitromortac Should be ready for review now. Ended up refactoring and optimizing a bit - left individual comments to make it more straightforward to review, and take out any change you don't agree with. Squash away before merge :)

Set a minor python version for the base images as breakages in python libraries do happen; better safe than sorry.
New build-arg `LNDMANAGE_EXTRA_PACKAGES`; empty by default but fish is still there by default for `build.sh` builds.
Should also be cleaner to build directly from the root without using the script now, for those who prefer it.

I'm not really using `run-lndmanage` but templating in the config through other means, so please make sure nothing breaks for you as well. Running fine here.

Image size reduced from 1.1G to 300MB.

**Comment by 3nprob** [comment]
Also I *really* think it shouldn't run as root by default but I guess that goes in a separate PR to not make the review too messy ^^

Can make that once this one's sorted out

**Comment by bitromortac** [comment]
Hey, appreciate your contributions a lot! I'll have more time to review next week. Perhaps I can get to some of it earlier.

**Comment by 3nprob** [comment]
Aight, thanks for the update  :)
The PRs should be independent enough so you can take  them one-by-one

File: docker/Dockerfile [hunk 6]
```diff
@@ -1,47 +1,48 @@
...
 
-FROM python:3 as builder
+FROM python:3.10-slim as builder
 
 RUN python -m venv /root/.venv
 
 ENV PATH="/root/.venv/bin:$PATH"
 
-ARG LNDMANAGE_HOST_SRC_PATH
+ARG LNDMANAGE_HOST_SRC_PATH .
```
Comment (bitromortac) [inline docker/Dockerfile]: The dot seems not to be needed (got a syntax error), same below? https://docs.docker.com/engine/reference/builder/#arg

File: docker/Dockerfile [hunk 7]
```diff
@@ -1,47 +1,48 @@
...
 ENV PATH="/root/.venv/bin:$PATH:/root"
-env TLS_CERT_FILE /root/aux/tls.cert
-env ADMIN_MACAROON_FILE /root/aux/admin.macaroon
+ENV TLS_CERT_FILE /root/aux/tls.cert
+ENV ADMIN_MACAROON_FILE /root/aux/admin.macaroon
 
 # copy sources under /root/lndmanage
 WORKDIR /root/lndmanage
-ARG LNDMANAGE_HOST_SRC_PATH
+ARG LNDMANAGE_HOST_SRC_PATH .
```
Comment (bitromortac) [inline docker/Dockerfile]: See above

**Review by bitromortac — COMMENTED** [review]
Cool, I like the reduction in image size :rocket:. Changes look good! A minor remark is that it would be good to persist the lndmanage.log file across runs, but that's not a blocker.

File: docker/Dockerfile (hunk 6 above)
Comment (3nprob) [reply docker/Dockerfile]: Maybe because of differing docker versions that I don't get an error here; either way, just pushed a fix with the correct syntax.

**Comment by bitromortac** [comment]
Great work, very appreciated! :tada:

**Comment by jaonoctus** [comment]
Well done guys!
